name: Build
on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        test-java-version:
          - 8
          - 11
    steps:
      - uses: actions/checkout@v3
      - id: setup-java
        name: Set up Java ${{ matrix.test-java-version }} for tests
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.test-java-version }}
          cache: 'maven'

      - name: Build base
        if: ${{ steps.setup-java.outputs.cache-hit != 'true' }}
        run: |
          mvn -B install -DskipTests -Dmaven.javadoc.skip=true dependency:go-offline

      - name: print
        run: mvn --version

      - name: test
        run: |
          mvn -B -Dmaven.javadoc.skip=true verify